### ISSUE TITLE
Adding a user doesn't work

### ISSUE THREAD

**Issue by klingtnet** [urandom/readeef#12]
I've successfully installed the user-admin tool but I wasn't able to create a new user (setting a new password worked, besides that I couldn't login #11) :

```sh
$ sudo readeef-user-admin --config /etc/readeef/readeef.cfg add myuser somepassword
Error setting password for user 'myuser': Invalid user login
```

I've tested various user/password combinations but nothing worked. The error is shown if the [username was empty](https://github.com/urandom/readeef/blob/e34c04dbe0affc4abf6e00691ec80801f20b37c0/content/base/user.go#L70) which it clearly wasn't.

For me it was a bit unintuitive to have the user managment in a seperate tool. I don't want to question any design choices, but a `readeef` user should be able to change the admin password without installing an extra tool. If this is possible without installing the `user-admin`, then please let me know.

**Comment by urandom** [comment]
Actually, the admin tool isn't necessary. There's already a default admin user present in the system, and you can add and remove non-admin users from the GUI. And of course, you can change the default admin user's password from the GUI itself. It's all under 'settings'.

Though it seems there's something fundamentally broken on your machine, could be as a result of my arch linux package, since I gathered you were unable to install it via `go get`.

**Comment by klingtnet** [comment]
I didn't know that there was a administration section in the web interface until I tested the `go get` version since #13 was fixed.
The problem is possibly related to the `1.1.0` release. The version from `master` (installed via `go get`) runs fine when started from `/usr/bin`:

```sh
$ go get -u github.com/urandom/readeef/cmd/readeef-server
$ sudo cp $(which readeef-server) /usr/bin/readeef
$ /usr/bin/readeef -config /tmp/readeef.cfg
```
