### ISSUE TITLE
cannot add feed

### ISSUE THREAD

**Issue by ghost** [urandom/readeef#35]
Hi,

Hope you are all well !

I cannot add this feed.
https://www.hackerfactor.com/blog/index.php?/feeds/index.rss1
neither this one too
https://www.hackerfactor.com/blog/index.php?/feeds/index.rss2

Any reason why ?

Thanks in advance.

Cheers,
X

**Comment by urandom** [comment]
@x0rzkov 

Would you be able to provide the log output around the time when you tried to add them?

**Comment by x0rzkov** [comment]
on the cli logs:
```bash
INFO Getting user admin                           
INFO Getting user admin                           
INFO Getting user admin                           
INFO Getting user admin                           
INFO Getting user admin feeds                     
INFO Searching for feeds from url https://www.hackerfactor.com/blog/index.php?/feeds/index.rss1 
```

on the front-end:
Discover/import feeds
No new feeds found

**Comment by x0rzkov** [comment]
I have the same with this feed too: https://singularityhub.com/feed/

I tried with https://github.com/mmcdole/gofeed and it parses it without problem.

**Comment by urandom** [comment]
It looks like the problem is that the server doesn't allow the connection. I got a "403 Bad Bot" response a few times before the connection started being cut off by the server with an error "connection reset by peer"

It could be that they are expecting some sort of header, and if not present, are preventing the connection.
